- name: Install the nginx  unzip
  become: true
  ansible.builtin.yum:
    name:          
      - nginx
      - unzip
    state: present

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/VKCOM/lighthouse/archive/refs/heads/master.zip
    dest: /usr/share   #/usr/share/lighthouse-master/
    remote_src: yes

- name: Template  config_file
  become: true
  ansible.builtin.template:
    src:  ./templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  notify:
    - Restart nginx  